language: node_js
node_js: node

sudo: false
dist: trusty

env:
  global:
    secure: QwnXsCYkcEftTWJShEVjVWuSkGu87sv/3yHx+JRPkdoqUHDlmWrS3Rl0LMBoJi9dJ/G7mIslKs89bzP0c8iPRiccwbc0tz/6AWwPYGYj7cHZcbH7wA0WEUpmOEO98I5x0Li6n+NK4DPTJTvGJjfWx4AQ4iTtsz/hTHDGYtMQuoY=

script: npm run build
before_deploy:
  - curl --location --retry 5 --output OSS_Python_API_20160419.zip 'https://docs-aliyun.cn-hangzhou.oss.aliyun-inc.com/internal/oss/0.0.4/assets/sdk/OSS_Python_API_20160419.zip?spm=5176.doc32171.2.2.Q9k9H5&file=OSS_Python_API_20160419.zip'
  - unzip OSS_Python_API_20160419.zip
deploy:
  provider: script
  script: python osscmd uploadfromdir aot oss://mycard/store --id=$ALIYUN_ID --key=$ALIYUN_SECRET
  skip_cleanup: true
  on:
    branch: master
